### ISSUE TITLE
V9, Custom Hotbar pushes normal hotbar out of bounds

### ISSUE THREAD

**Issue by apoapostolov** [Norc/foundry-custom-hotbar#106]
![image](https://user-images.githubusercontent.com/4083812/146689833-ca227b02-2047-4095-a715-35f4717b5f8e.png)

**Comment by Norc** [comment]
Hello,
You can manually adjust the location of the custom hotbar using the settings. In this case, it looks like you need to increase its x position by like 75 and Y positions by 5 or so, but you can move this exactly where you'd like again. 

Not sure why it is in a different location though, so I'll keep an eye on it and see if I can repro without any other modules active.

Thanks for the report! Feel free to reopen if you have difficulties configuring your hotbar to the desired location.
