### ISSUE TITLE
Bug with removing macros

### ISSUE THREAD

**Issue by Norc** [Norc/foundry-custom-hotbar#112]
Report of removing a macro from the custom hotbar also removing it from the core hotbar.

**Comment by Daso78** [comment]
I'm getting this as well. Removing a macro from the custom hotbar position 1 removes the macro from the Foundry position 1 and leaves the macro on the custom hot bar with no way of removing the macro.

**Comment by colinbate** [comment]
Yes, I'm seeing this as well.

**Comment by Norc** [comment]
should be fixed in upcoming v10 version.
