### ISSUE TITLE
Manifests on Foundry VTT for old versions are not correct

### ISSUE THREAD

**Issue by SapereAude1490** [Norc/foundry-custom-hotbar#116]
Hey, not really a bug, just wanted to tell you that the manifest links for the older versions on https://foundryvtt.com/packages/custom-hotbar are not correct (all pointing to the newest version).

I made my own manifest to get around it and download the 2.1.0 version.

**Comment by Norc** [comment]
Thanks, yes, it's on the list to fix in the (very) near future. Tomorrow
*hopefully*

**Comment by Norc** [comment]
I *think* I fixed this, will reopen if i didn't.
