### ISSUE TITLE
Macros on the custom hotbar can't be removed

### ISSUE THREAD

**Issue by SalieriC** [Norc/foundry-custom-hotbar#117]
If a macro is on both hotbars, the one from the core hotbar is removed, when the macro is only on the custom hotbar, nothing happens at all when trying to remove it.

**Comment by LukasPrism** [comment]
I'm having the same issue. Is this module still being maintained?

**Comment by CainesNyx** [comment]
Yep. Same as SalieriC.

**Comment by Norc** [comment]
> I'm having the same issue. Is this module still being maintained? Would love to use it, but at the moment it doesn't seem possible.

@SalieriC @LukasPrism @CainesNyx Thanks for the report. My v9 update hadn't quite resolved the compatibility changes and then life has been crazy.

The good news is that things are calming down again and this module will be updated for v10 (and probably a final v9 release also) soon.

**Comment by LukasPrism** [comment]
Oh that’s wonderful news. Thanks so much!

**Comment by Norc** [comment]
Resolved in the in-progress v10 compatible version.
