### ISSUE TITLE
Firefox Developer Edition Drag and Drop incompatibility

### ISSUE THREAD

**Issue by Norc** [Norc/foundry-custom-hotbar#25]
User @Erunseelie#2077 reports the following error when dragging and dropping onto the core hotbar from any location in a clean test world (CHB 1.5.0, F 0.6.4, DND 0.93):

I see this error appearing in the browser console:
TypeError: An error occurred while rendering CustomHotbar 69: can't access property "preventDefault", event is undefined

Per Stan:
@Norc just check if event is null/undefined and only call that line if it’s defined.

**Comment by Norc** [comment]
possibly fixed in 2.0, retest.

**Comment by Kazpers** [comment]
Can confirm this happens in normal Firefox 78 making a hard incompatibility between Firefox and Custom Toolbar. Hope to see this fixed soon...

**Comment by Norc** [comment]
Thanks so much for the additional info! I have a major release planned within a week, hopefully sooner, and I'll add it in for that.

The version number and less obscure browser will be helpful for testing.

**Comment by Norc** [comment]
This is hopefully fixed with this alpha version, if you could give it a run I'd be much obliged, thanks!

https://raw.githubusercontent.com/Norc/foundry-custom-hotbar/dev/module.json.

**Comment by Kazpers** [comment]
Just tested this quickly. It seems to work. I can copy macros to the custom hotbar, edit them, and execute them without issues in Firefox 78.

Thank you for the great and fast work :)
