### ISSUE TITLE
renderCustomHotbar is not called on all clients

### ISSUE THREAD

**Issue by janssen-io** [Norc/foundry-custom-hotbar#3]
The `renderHotbar` hook is called on all clients to delete macros that were deleted by another player. 

Token Hotbar also assumes that `renderHotbar` (or in your case `renderCustomHotbar`) is called on all clients to force a refresh when the shared hotbar is changed.

While the Custom Hotbar re-renders nicely when a macro is deleted, it should also re-render for other players when a player adjusts their own custom hotbar to stay inline with the behavior of `renderHotbar`.

**Comment by Norc** [comment]
From what I understand, I cleverly fixed this by doing nothing. Please re-log if this turns out to not be correct.
