### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by DarKDinDoN** [Norc/foundry-custom-hotbar#43]
Hello,

Thx for that awesome module!
It doesn't work on FF. Not possible to drag macros to the hotbar or minimize the hotbar.

**Comment by DarKDinDoN** [comment]
Might be related to this:
```javascript
TypeError: An error occurred while rendering CustomHotbar 57: event is undefined
    activateListeners https://cos.darkgames.space/modules/custom-hotbar/custom-hotbar.js:255
    _render https://cos.darkgames.space/scripts/foundry.js:3889
foundry.js:3833:14
```

**Comment by Norc** [comment]
Hello, thanks for the kind words and the report!

I just fixed this today. There is a dev build available with the fix if you want to use it in the meantime here https://raw.githubusercontent.com/Norc/foundry-custom-hotbar/dev/module.json. 

I will be releasing the fix in the new version this weekend, please let me know if this doesn't resolve your issue. Thanks!
