### ISSUE TITLE
Not working in Firefox

### ISSUE THREAD

**Issue by DarKDinDoN** [Norc/foundry-custom-hotbar#53]
Hello,

Last version is still not working with FF.
This time the hotbar isn't visible at all.

FF 78.0.2 (64 bits)

**Comment by Norc** [comment]
Yikes, thanks for the report. Can you contact me on discord (Norc#5108)?

**Comment by Norc** [comment]
Also, can you hit F12 to see if there are any errors in the console while it is the only mod?

I tested versions very similar to the final release in Firefox, but not the final release itself, so it's possible I missed something.

**Comment by Norc** [comment]
Discussed in Discord. No errors in console, renders in Chrome normally, and the regular Hotbar renders normally also. Will look into this tomorrow.

**Comment by Norc** [comment]
Thanks for logging in Foundry GitLab (https://gitlab.com/foundrynet/foundryvtt/-/issues/3272). Issue seems to be that the hook I need is not fired on FireFox only, somehow... though I think I may know why.

I'll create a workaround and do some more testing on the underlying problem soon.

**Comment by Norc** [comment]
should be fixed in 2.0.2. Will follow up with Foundry bug separately.
