### ISSUE TITLE
Regular hotbar tooltip/ menu behind custom hotbar and unclickable

### ISSUE THREAD

**Issue by JustNoon** [Norc/foundry-custom-hotbar#67]
![image](https://user-images.githubusercontent.com/45368472/89101738-4a330900-d3c8-11ea-8428-1eb5e3b500d8.png)
Fix: `#custom-hotbar {
    z-index: 69
}`

**Comment by Norc** [comment]
Can you confirm that you are on v2.0.5? That fix should already be live in
it.

Please feel free to contact me on Discord if you are having issues updating
to v2.0.5 or if you are on v2.0.5 and the z-index is still wrong. Thanks!

**Comment by JustNoon** [comment]
Ah. I forgot to check the current release here on github. You're correct, I'm on v2.0.4.

v2.0.5 does not get applied through the "Check for updates" or "update all" button. It says I'm on the latest version.
Should I reinstall or just apply the current manifest?

**Comment by Norc** [comment]
Please uninstall and reinstall. That's odd that it's not auto-updating,
I'll have to investigate that issue. Unfortunate, that.

-Dan

**Comment by JustNoon** [comment]
Both ways seemed to work for me. I made sure to do the reinstall as the second step in case the manifest put me on a manual updates track or something. I wonder if there's a caching issue for checking for updates. Could even be just checking the day the update came out instead. Who knows. Thanks!
