### ISSUE TITLE
Shift+Number doesn't wok in Shadow of the Demon Lord

### ISSUE THREAD

**Issue by aeciobf** [Norc/foundry-custom-hotbar#71]
Shift+Number doesn't wok in Shadow of the Demon Lord

**Comment by Norc** [comment]
Hi, thanks for the report. Does nothing happen when you press the keys? Are there any errors in the console?

I'll check it out when I return to Custom Hotbar development in a week or two, thanks!

**Comment by aeciobf** [comment]
Oh, sorry.
I forgot upload the error printscreen.



![error](https://user-images.githubusercontent.com/2878022/91660781-238eed80-eaae-11ea-8852-192bbcee1d1c.png)

**Comment by nihilistkitten** [comment]
+1.

Seems like `chbKeyEnabled` should be commented out on line 109, since its implementation is commented out as well:
https://github.com/Norc/foundry-custom-hotbar/blob/497a9ce42d4af72bf079f411881c9a4a1d3ebd8d/scripts/custom-hotbar-settings.js#L29-L43

Seems like a mostly easy temporary fix - I can write a PR if you want.

**Comment by LadySaga** [comment]
I have this issue too, but my console error looks slightly different on row 2 and 3.

> Uncaught ReferenceError: chbKeyEnabled is not defined
>     at index.js:109
> (anonymous) @ index.js:109

The result is that I simply can't use the shift+# hotkeys at all.
I can still **click** the macro, but no hotkey.

**Comment by Norc** [comment]
Hey folks, thanks for all the feedback on this. Custom Hotbar is finally up next in my queue again and I'll have a new 0.7.4 compatible version out in a few days with this fix and a few others.

**Comment by LadySaga** [comment]
Great to hear. Will that fix also apply to us safer users who stay on 0.6.6 stable until the new smashing 0.7.# is released? :)

**Comment by Norc** [comment]
Yeah, I'll make some effort to make it 0.6.6 friendly if it's not an unusually large effort to do so.

For what it's worth, according to what Atro said on the livestream today 0.7.5, the stable release, is tentativesly slotted for release on approximately Wednesday October 21st, so... verrrry soon.

**Comment by LadySaga** [comment]
Oh, and sidenote, congrats! I saw you got promoted to moderator on the discord too! :)

**Comment by Norc** [comment]
This  looks to be fixed for the next release, thanks for the help and patience with this one and sorry it took so long!
