### ISSUE TITLE
Feature Request - Add setting for auto collapse

### ISSUE THREAD

**Issue by Jonwh25** [Norc/foundry-custom-hotbar#75]
Some of my players have smaller monitors and they told me they don't want to use the hotbar, while the other have love it. The ones that don't want to see it since they have small monitors asked if there was a way to have it be auto collapsed instead of having to click on it to collapse it.  So their default setting would be collapsed.

**Comment by Norc** [comment]
Okay, I can do that. What about an option to disable it entirely?

**Comment by Jonwh25** [comment]
Right on! Thanks

**Comment by Norc** [comment]
Closing in favor of the further-reaching change in #72 . Will reopen if this is requested again separately.
