### ISSUE TITLE
Add other keybind options instead of Shift-x, particularly for Better Rolls users

### ISSUE THREAD

**Issue by Norc** [Norc/foundry-custom-hotbar#79]
Chartoxic#9871 points out that the shift option is not great with better rolls and rolls twice every time. Perhaps CTRL-Num or ideally a fully configurable keybind.

**Comment by ghost91-** [comment]
I think there are 2 modules right now that support adding (and I think also configuring) arbitrary keybindings. Might be worth taking a look at them:
- https://github.com/flamewave000/dragonflagon-fvtt/tree/master/lib-df-hotkeys
- https://gitlab.com/fvtt-modules-lab/keybind-lib

**Comment by Norc** [comment]
Should be resolved by now using the DF Hotkeys module, thanks for the recommendation Ghost91.
