### ISSUE TITLE
Console is flooded with Custom Hotbar debug events

### ISSUE THREAD

**Issue by websterguy** [Norc/foundry-custom-hotbar#84]
The console becomes filled with debug messages about Event keycodes when typing and Macro tooltip and Mouse out events when moving the mouse over the bar.

**Comment by Norc** [comment]
thanks, I'm long overdue for an update here. I'll make sure this gets into it, you are correct that it's really bad form.

Thanks for the feedback and for checking out the module!

**Comment by ghost91-** [comment]
One idea would be to use https://foundryvtt.com/packages/_dev-mode to enable / disable debug messages.

**Comment by Norc** [comment]
resolved by creating custom debug function.
