### ISSUE TITLE
Shift + button results in macro running twice

### ISSUE THREAD

**Issue by Norc** [Norc/foundry-custom-hotbar#85]
I haven't had a chance to verify this myself yet, but, per NeekoKnight#2102

> NeekoKnightToday at 2:19 PM
> Hey, sorry to message you about this but I can't find any information. When using Custom Hotbars, do you have any idea why when I use Shift+any number, it activates the macro twice?
> [...]
> It does still do it when all other modules are off. It works fine with a mouse click and it's not my keyboard acting up.
> I'm using DnD5e 1.2.4...

**Comment by ghost91-** [comment]
This might also be fixed by using one of the keybind modules i mentioned in #79

**Comment by Norc** [comment]
Should be resolved by now using the DF Hotkeys module, thanks for the recommendation Ghost91.
