### ISSUE TITLE
Can't update beyond release 2.0.6

### ISSUE THREAD

**Issue by Stendarpaval** [Norc/foundry-custom-hotbar#89]
The changelog and module.json suggest that there's a new release, namely version 2.1.0. Foundry does see that a new update is available, but it just reinstalls release 2.0.6 again, probably because that's what the download url in the module.json still points to: 
https://github.com/Norc/foundry-custom-hotbar/blob/d6129920fd85e8308e6957bd8f9e25b3f23a5ca8/module.json#L29

I might be mistaken, but I figured you might have missed that when updating module.json.

**Comment by Norc** [comment]
Ha, nope, not quite yet, thanks for your interest though! it should be ready later tonight EST.

I was being sloppy/lazy getting going again and I was working in Master and figured Id be fine so long as I didn't update the downloadable zip. Didn't realize that the version number change would be picked up by the Foundry client, but that makes total sense. I'll fix that quick until I'm ready to deploy (and work in Dev first next time like I should have to begin with).

Thanks for the report, and sorry about that!

**Comment by Norc** [comment]
Changed module.json and changelog.md to stop telling you lies.

I'm closing, but feel free to reopen if you think I can do something else to make this less confusing until the actual 2.10 release (short of backing out all my changes and moving to dev branch like I should have from the start, too much bother at this point).

Thanks again!!

**Comment by Stendarpaval** [comment]
Seems like your change fixed the issue, Foundry no longer thinks there's an update :)

And you're very welcome, I haven't figured out how to do these fancy Github Actions to make releases yet either, which is what many other Foundry module developers seem to be using. 

I personally only commit changes to the repo when it's close to a release, and let the code live on my machine until then. Though a dev branch could also work, I guess! 

Anyhow, no need to reopen this issue I think. It's nice to hear that you're getting back to development again, so be sure to take it easy :).
